/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables;


import cn.bcd.lib.jooq.generate.Bcd;
import cn.bcd.lib.jooq.generate.Keys;
import cn.bcd.lib.jooq.generate.tables.records.TSysPermissionRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * 角色与权限关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysPermission extends TableImpl<TSysPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bcd.t_sys_permission</code>
     */
    public static final TSysPermission T_SYS_PERMISSION = new TSysPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysPermissionRecord> getRecordType() {
        return TSysPermissionRecord.class;
    }

    /**
     * The column <code>bcd.t_sys_permission.id</code>. id
     */
    public final TableField<TSysPermissionRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "id");

    /**
     * The column <code>bcd.t_sys_permission.name</code>. 权限名称
     */
    public final TableField<TSysPermissionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(20).nullable(false), this, "权限名称");

    /**
     * The column <code>bcd.t_sys_permission.resource</code>. 资源
     */
    public final TableField<TSysPermissionRecord, String> RESOURCE = createField(DSL.name("resource"), SQLDataType.VARCHAR(100).nullable(false), this, "资源");

    /**
     * The column <code>bcd.t_sys_permission.create_time</code>. 创建时间
     */
    public final TableField<TSysPermissionRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>bcd.t_sys_permission.create_user_id</code>. 创建人id
     */
    public final TableField<TSysPermissionRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "创建人id");

    /**
     * The column <code>bcd.t_sys_permission.create_user_name</code>. 创建人姓名
     */
    public final TableField<TSysPermissionRecord, String> CREATE_USER_NAME = createField(DSL.name("create_user_name"), SQLDataType.VARCHAR(50), this, "创建人姓名");

    /**
     * The column <code>bcd.t_sys_permission.update_time</code>. 更新时间
     */
    public final TableField<TSysPermissionRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0), this, "更新时间");

    /**
     * The column <code>bcd.t_sys_permission.update_user_id</code>. 更新人id
     */
    public final TableField<TSysPermissionRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "更新人id");

    /**
     * The column <code>bcd.t_sys_permission.update_user_name</code>. 更新人姓名
     */
    public final TableField<TSysPermissionRecord, String> UPDATE_USER_NAME = createField(DSL.name("update_user_name"), SQLDataType.VARCHAR(50), this, "更新人姓名");

    private TSysPermission(Name alias, Table<TSysPermissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TSysPermission(Name alias, Table<TSysPermissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("角色与权限关系表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bcd.t_sys_permission</code> table reference
     */
    public TSysPermission(String alias) {
        this(DSL.name(alias), T_SYS_PERMISSION);
    }

    /**
     * Create an aliased <code>bcd.t_sys_permission</code> table reference
     */
    public TSysPermission(Name alias) {
        this(alias, T_SYS_PERMISSION);
    }

    /**
     * Create a <code>bcd.t_sys_permission</code> table reference
     */
    public TSysPermission() {
        this(DSL.name("t_sys_permission"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Bcd.BCD;
    }

    @Override
    public Identity<TSysPermissionRecord, ULong> getIdentity() {
        return (Identity<TSysPermissionRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<TSysPermissionRecord> getPrimaryKey() {
        return Keys.KEY_T_SYS_PERMISSION_PRIMARY;
    }

    @Override
    public TSysPermission as(String alias) {
        return new TSysPermission(DSL.name(alias), this);
    }

    @Override
    public TSysPermission as(Name alias) {
        return new TSysPermission(alias, this);
    }

    @Override
    public TSysPermission as(Table<?> alias) {
        return new TSysPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysPermission rename(String name) {
        return new TSysPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysPermission rename(Name name) {
        return new TSysPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysPermission rename(Table<?> name) {
        return new TSysPermission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysPermission where(Condition condition) {
        return new TSysPermission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysPermission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysPermission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysPermission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysPermission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysPermission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysPermission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysPermission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysPermission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysPermission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
