/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables;


import cn.bcd.lib.jooq.generate.Bcd;
import cn.bcd.lib.jooq.generate.Keys;
import cn.bcd.lib.jooq.generate.tables.records.TSysRoleMenuRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 角色与菜单关联关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysRoleMenu extends TableImpl<TSysRoleMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bcd.t_sys_role_menu</code>
     */
    public static final TSysRoleMenu T_SYS_ROLE_MENU = new TSysRoleMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysRoleMenuRecord> getRecordType() {
        return TSysRoleMenuRecord.class;
    }

    /**
     * The column <code>bcd.t_sys_role_menu.role_id</code>. 关联角色id
     */
    public final TableField<TSysRoleMenuRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "关联角色id");

    /**
     * The column <code>bcd.t_sys_role_menu.menu_id</code>. 关联菜单id
     */
    public final TableField<TSysRoleMenuRecord, Long> MENU_ID = createField(DSL.name("menu_id"), SQLDataType.BIGINT.nullable(false), this, "关联菜单id");

    private TSysRoleMenu(Name alias, Table<TSysRoleMenuRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TSysRoleMenu(Name alias, Table<TSysRoleMenuRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("角色与菜单关联关系表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bcd.t_sys_role_menu</code> table reference
     */
    public TSysRoleMenu(String alias) {
        this(DSL.name(alias), T_SYS_ROLE_MENU);
    }

    /**
     * Create an aliased <code>bcd.t_sys_role_menu</code> table reference
     */
    public TSysRoleMenu(Name alias) {
        this(alias, T_SYS_ROLE_MENU);
    }

    /**
     * Create a <code>bcd.t_sys_role_menu</code> table reference
     */
    public TSysRoleMenu() {
        this(DSL.name("t_sys_role_menu"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Bcd.BCD;
    }

    @Override
    public UniqueKey<TSysRoleMenuRecord> getPrimaryKey() {
        return Keys.KEY_T_SYS_ROLE_MENU_PRIMARY;
    }

    @Override
    public TSysRoleMenu as(String alias) {
        return new TSysRoleMenu(DSL.name(alias), this);
    }

    @Override
    public TSysRoleMenu as(Name alias) {
        return new TSysRoleMenu(alias, this);
    }

    @Override
    public TSysRoleMenu as(Table<?> alias) {
        return new TSysRoleMenu(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysRoleMenu rename(String name) {
        return new TSysRoleMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysRoleMenu rename(Name name) {
        return new TSysRoleMenu(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysRoleMenu rename(Table<?> name) {
        return new TSysRoleMenu(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRoleMenu where(Condition condition) {
        return new TSysRoleMenu(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRoleMenu where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRoleMenu where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRoleMenu where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysRoleMenu where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysRoleMenu where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysRoleMenu where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysRoleMenu where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRoleMenu whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRoleMenu whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
