/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables;


import cn.bcd.lib.jooq.generate.Bcd;
import cn.bcd.lib.jooq.generate.Keys;
import cn.bcd.lib.jooq.generate.tables.records.TSysUserRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * 用户基础信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysUser extends TableImpl<TSysUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bcd.t_sys_user</code>
     */
    public static final TSysUser T_SYS_USER = new TSysUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysUserRecord> getRecordType() {
        return TSysUserRecord.class;
    }

    /**
     * The column <code>bcd.t_sys_user.id</code>. 主键
     */
    public final TableField<TSysUserRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>bcd.t_sys_user.username</code>. 用户名
     */
    public final TableField<TSysUserRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(50).nullable(false), this, "用户名");

    /**
     * The column <code>bcd.t_sys_user.password</code>. 密码
     */
    public final TableField<TSysUserRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(100).nullable(false), this, "密码");

    /**
     * The column <code>bcd.t_sys_user.email</code>. 邮箱
     */
    public final TableField<TSysUserRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "邮箱");

    /**
     * The column <code>bcd.t_sys_user.phone</code>. 手机号
     */
    public final TableField<TSysUserRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(11), this, "手机号");

    /**
     * The column <code>bcd.t_sys_user.real_name</code>. 真实姓名
     */
    public final TableField<TSysUserRecord, String> REAL_NAME = createField(DSL.name("real_name"), SQLDataType.VARCHAR(50), this, "真实姓名");

    /**
     * The column <code>bcd.t_sys_user.sex</code>. 性别
     */
    public final TableField<TSysUserRecord, String> SEX = createField(DSL.name("sex"), SQLDataType.VARCHAR(5), this, "性别");

    /**
     * The column <code>bcd.t_sys_user.birthday</code>. 生日
     */
    public final TableField<TSysUserRecord, LocalDateTime> BIRTHDAY = createField(DSL.name("birthday"), SQLDataType.LOCALDATETIME(0), this, "生日");

    /**
     * The column <code>bcd.t_sys_user.card_number</code>. 身份证号
     */
    public final TableField<TSysUserRecord, String> CARD_NUMBER = createField(DSL.name("card_number"), SQLDataType.VARCHAR(20), this, "身份证号");

    /**
     * The column <code>bcd.t_sys_user.status</code>. 是否可用(1:可用,0:禁用)
     */
    public final TableField<TSysUserRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "是否可用(1:可用,0:禁用)");

    /**
     * The column <code>bcd.t_sys_user.create_time</code>. 创建时间
     */
    public final TableField<TSysUserRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0), this, "创建时间");

    /**
     * The column <code>bcd.t_sys_user.create_user_id</code>. 创建人id
     */
    public final TableField<TSysUserRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "创建人id");

    /**
     * The column <code>bcd.t_sys_user.create_user_name</code>. 创建人姓名
     */
    public final TableField<TSysUserRecord, String> CREATE_USER_NAME = createField(DSL.name("create_user_name"), SQLDataType.VARCHAR(50), this, "创建人姓名");

    /**
     * The column <code>bcd.t_sys_user.update_time</code>. 更新时间
     */
    public final TableField<TSysUserRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0), this, "更新时间");

    /**
     * The column <code>bcd.t_sys_user.update_user_id</code>. 更新人id
     */
    public final TableField<TSysUserRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "更新人id");

    /**
     * The column <code>bcd.t_sys_user.update_user_name</code>. 更新人姓名
     */
    public final TableField<TSysUserRecord, String> UPDATE_USER_NAME = createField(DSL.name("update_user_name"), SQLDataType.VARCHAR(50), this, "更新人姓名");

    private TSysUser(Name alias, Table<TSysUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TSysUser(Name alias, Table<TSysUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户基础信息表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bcd.t_sys_user</code> table reference
     */
    public TSysUser(String alias) {
        this(DSL.name(alias), T_SYS_USER);
    }

    /**
     * Create an aliased <code>bcd.t_sys_user</code> table reference
     */
    public TSysUser(Name alias) {
        this(alias, T_SYS_USER);
    }

    /**
     * Create a <code>bcd.t_sys_user</code> table reference
     */
    public TSysUser() {
        this(DSL.name("t_sys_user"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Bcd.BCD;
    }

    @Override
    public Identity<TSysUserRecord, ULong> getIdentity() {
        return (Identity<TSysUserRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<TSysUserRecord> getPrimaryKey() {
        return Keys.KEY_T_SYS_USER_PRIMARY;
    }

    @Override
    public TSysUser as(String alias) {
        return new TSysUser(DSL.name(alias), this);
    }

    @Override
    public TSysUser as(Name alias) {
        return new TSysUser(alias, this);
    }

    @Override
    public TSysUser as(Table<?> alias) {
        return new TSysUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysUser rename(String name) {
        return new TSysUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysUser rename(Name name) {
        return new TSysUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysUser rename(Table<?> name) {
        return new TSysUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUser where(Condition condition) {
        return new TSysUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
