/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables;


import cn.bcd.lib.jooq.generate.Bcd;
import cn.bcd.lib.jooq.generate.Keys;
import cn.bcd.lib.jooq.generate.tables.records.TSysMenuRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * 菜单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysMenu extends TableImpl<TSysMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bcd.t_sys_menu</code>
     */
    public static final TSysMenu T_SYS_MENU = new TSysMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysMenuRecord> getRecordType() {
        return TSysMenuRecord.class;
    }

    /**
     * The column <code>bcd.t_sys_menu.id</code>. 主键
     */
    public final TableField<TSysMenuRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>bcd.t_sys_menu.parent_id</code>. 父菜单id
     */
    public final TableField<TSysMenuRecord, Long> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.BIGINT, this, "父菜单id");

    /**
     * The column <code>bcd.t_sys_menu.name</code>. 菜单名称
     */
    public final TableField<TSysMenuRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "菜单名称");

    /**
     * The column <code>bcd.t_sys_menu.url</code>. url地址
     */
    public final TableField<TSysMenuRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(256), this, "url地址");

    /**
     * The column <code>bcd.t_sys_menu.icon</code>. 图标
     */
    public final TableField<TSysMenuRecord, String> ICON = createField(DSL.name("icon"), SQLDataType.VARCHAR(256), this, "图标");

    /**
     * The column <code>bcd.t_sys_menu.order_num</code>. 排序
     */
    public final TableField<TSysMenuRecord, Integer> ORDER_NUM = createField(DSL.name("order_num"), SQLDataType.INTEGER.nullable(false), this, "排序");

    /**
     * The column <code>bcd.t_sys_menu.create_time</code>. 创建时间
     */
    public final TableField<TSysMenuRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>bcd.t_sys_menu.create_user_id</code>. 创建人id
     */
    public final TableField<TSysMenuRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "创建人id");

    /**
     * The column <code>bcd.t_sys_menu.create_user_name</code>. 创建人姓名
     */
    public final TableField<TSysMenuRecord, String> CREATE_USER_NAME = createField(DSL.name("create_user_name"), SQLDataType.VARCHAR(50), this, "创建人姓名");

    /**
     * The column <code>bcd.t_sys_menu.update_time</code>. 更新时间
     */
    public final TableField<TSysMenuRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0), this, "更新时间");

    /**
     * The column <code>bcd.t_sys_menu.update_user_id</code>. 更新人id
     */
    public final TableField<TSysMenuRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "更新人id");

    /**
     * The column <code>bcd.t_sys_menu.update_user_name</code>. 更新人姓名
     */
    public final TableField<TSysMenuRecord, String> UPDATE_USER_NAME = createField(DSL.name("update_user_name"), SQLDataType.VARCHAR(50), this, "更新人姓名");

    private TSysMenu(Name alias, Table<TSysMenuRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TSysMenu(Name alias, Table<TSysMenuRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("菜单表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bcd.t_sys_menu</code> table reference
     */
    public TSysMenu(String alias) {
        this(DSL.name(alias), T_SYS_MENU);
    }

    /**
     * Create an aliased <code>bcd.t_sys_menu</code> table reference
     */
    public TSysMenu(Name alias) {
        this(alias, T_SYS_MENU);
    }

    /**
     * Create a <code>bcd.t_sys_menu</code> table reference
     */
    public TSysMenu() {
        this(DSL.name("t_sys_menu"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Bcd.BCD;
    }

    @Override
    public Identity<TSysMenuRecord, ULong> getIdentity() {
        return (Identity<TSysMenuRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<TSysMenuRecord> getPrimaryKey() {
        return Keys.KEY_T_SYS_MENU_PRIMARY;
    }

    @Override
    public TSysMenu as(String alias) {
        return new TSysMenu(DSL.name(alias), this);
    }

    @Override
    public TSysMenu as(Name alias) {
        return new TSysMenu(alias, this);
    }

    @Override
    public TSysMenu as(Table<?> alias) {
        return new TSysMenu(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysMenu rename(String name) {
        return new TSysMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysMenu rename(Name name) {
        return new TSysMenu(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysMenu rename(Table<?> name) {
        return new TSysMenu(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenu where(Condition condition) {
        return new TSysMenu(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenu where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenu where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenu where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysMenu where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysMenu where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysMenu where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysMenu where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenu whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenu whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
