/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables;


import cn.bcd.lib.jooq.generate.Bcd;
import cn.bcd.lib.jooq.generate.Keys;
import cn.bcd.lib.jooq.generate.tables.records.TSysRoleRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysRole extends TableImpl<TSysRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bcd.t_sys_role</code>
     */
    public static final TSysRole T_SYS_ROLE = new TSysRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysRoleRecord> getRecordType() {
        return TSysRoleRecord.class;
    }

    /**
     * The column <code>bcd.t_sys_role.id</code>. 主键
     */
    public final TableField<TSysRoleRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>bcd.t_sys_role.name</code>. 角色名称
     */
    public final TableField<TSysRoleRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(20).nullable(false), this, "角色名称");

    /**
     * The column <code>bcd.t_sys_role.code</code>. 编码
     */
    public final TableField<TSysRoleRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).nullable(false), this, "编码");

    /**
     * The column <code>bcd.t_sys_role.remark</code>. 备注
     */
    public final TableField<TSysRoleRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.VARCHAR(256), this, "备注");

    /**
     * The column <code>bcd.t_sys_role.create_time</code>. 创建时间
     */
    public final TableField<TSysRoleRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>bcd.t_sys_role.create_user_id</code>. 创建人id
     */
    public final TableField<TSysRoleRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "创建人id");

    /**
     * The column <code>bcd.t_sys_role.create_user_name</code>. 创建人姓名
     */
    public final TableField<TSysRoleRecord, String> CREATE_USER_NAME = createField(DSL.name("create_user_name"), SQLDataType.VARCHAR(50), this, "创建人姓名");

    /**
     * The column <code>bcd.t_sys_role.update_time</code>. 更新时间
     */
    public final TableField<TSysRoleRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0), this, "更新时间");

    /**
     * The column <code>bcd.t_sys_role.update_user_id</code>. 更新人id
     */
    public final TableField<TSysRoleRecord, Long> UPDATE_USER_ID = createField(DSL.name("update_user_id"), SQLDataType.BIGINT, this, "更新人id");

    /**
     * The column <code>bcd.t_sys_role.update_user_name</code>. 更新人姓名
     */
    public final TableField<TSysRoleRecord, String> UPDATE_USER_NAME = createField(DSL.name("update_user_name"), SQLDataType.VARCHAR(50), this, "更新人姓名");

    private TSysRole(Name alias, Table<TSysRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TSysRole(Name alias, Table<TSysRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("角色表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bcd.t_sys_role</code> table reference
     */
    public TSysRole(String alias) {
        this(DSL.name(alias), T_SYS_ROLE);
    }

    /**
     * Create an aliased <code>bcd.t_sys_role</code> table reference
     */
    public TSysRole(Name alias) {
        this(alias, T_SYS_ROLE);
    }

    /**
     * Create a <code>bcd.t_sys_role</code> table reference
     */
    public TSysRole() {
        this(DSL.name("t_sys_role"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Bcd.BCD;
    }

    @Override
    public Identity<TSysRoleRecord, ULong> getIdentity() {
        return (Identity<TSysRoleRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<TSysRoleRecord> getPrimaryKey() {
        return Keys.KEY_T_SYS_ROLE_PRIMARY;
    }

    @Override
    public TSysRole as(String alias) {
        return new TSysRole(DSL.name(alias), this);
    }

    @Override
    public TSysRole as(Name alias) {
        return new TSysRole(alias, this);
    }

    @Override
    public TSysRole as(Table<?> alias) {
        return new TSysRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysRole rename(String name) {
        return new TSysRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysRole rename(Name name) {
        return new TSysRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysRole rename(Table<?> name) {
        return new TSysRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRole where(Condition condition) {
        return new TSysRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
