/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables;


import cn.bcd.lib.jooq.generate.Bcd;
import cn.bcd.lib.jooq.generate.Keys;
import cn.bcd.lib.jooq.generate.tables.records.TSysUserRoleRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户与角色关联关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysUserRole extends TableImpl<TSysUserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bcd.t_sys_user_role</code>
     */
    public static final TSysUserRole T_SYS_USER_ROLE = new TSysUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysUserRoleRecord> getRecordType() {
        return TSysUserRoleRecord.class;
    }

    /**
     * The column <code>bcd.t_sys_user_role.user_id</code>. 关联用户id
     */
    public final TableField<TSysUserRoleRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "关联用户id");

    /**
     * The column <code>bcd.t_sys_user_role.role_id</code>. 关联角色id
     */
    public final TableField<TSysUserRoleRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "关联角色id");

    private TSysUserRole(Name alias, Table<TSysUserRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TSysUserRole(Name alias, Table<TSysUserRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户与角色关联关系表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bcd.t_sys_user_role</code> table reference
     */
    public TSysUserRole(String alias) {
        this(DSL.name(alias), T_SYS_USER_ROLE);
    }

    /**
     * Create an aliased <code>bcd.t_sys_user_role</code> table reference
     */
    public TSysUserRole(Name alias) {
        this(alias, T_SYS_USER_ROLE);
    }

    /**
     * Create a <code>bcd.t_sys_user_role</code> table reference
     */
    public TSysUserRole() {
        this(DSL.name("t_sys_user_role"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Bcd.BCD;
    }

    @Override
    public UniqueKey<TSysUserRoleRecord> getPrimaryKey() {
        return Keys.KEY_T_SYS_USER_ROLE_PRIMARY;
    }

    @Override
    public TSysUserRole as(String alias) {
        return new TSysUserRole(DSL.name(alias), this);
    }

    @Override
    public TSysUserRole as(Name alias) {
        return new TSysUserRole(alias, this);
    }

    @Override
    public TSysUserRole as(Table<?> alias) {
        return new TSysUserRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysUserRole rename(String name) {
        return new TSysUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysUserRole rename(Name name) {
        return new TSysUserRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysUserRole rename(Table<?> name) {
        return new TSysUserRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUserRole where(Condition condition) {
        return new TSysUserRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUserRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUserRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUserRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysUserRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysUserRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysUserRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysUserRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUserRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysUserRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
