/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables;


import cn.bcd.lib.jooq.generate.Bcd;
import cn.bcd.lib.jooq.generate.Keys;
import cn.bcd.lib.jooq.generate.tables.records.TSysTaskRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysTask extends TableImpl<TSysTaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bcd.t_sys_task</code>
     */
    public static final TSysTask T_SYS_TASK = new TSysTask();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysTaskRecord> getRecordType() {
        return TSysTaskRecord.class;
    }

    /**
     * The column <code>bcd.t_sys_task.id</code>. 主键
     */
    public final TableField<TSysTaskRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>bcd.t_sys_task.name</code>. 任务名称
     */
    public final TableField<TSysTaskRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "任务名称");

    /**
     * The column <code>bcd.t_sys_task.status</code>.
     * 任务状态(1:等待中;2:执行中;3:任务被终止;4:已完成;5:执行失败)
     */
    public final TableField<TSysTaskRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false), this, "任务状态(1:等待中;2:执行中;3:任务被终止;4:已完成;5:执行失败)");

    /**
     * The column <code>bcd.t_sys_task.type</code>. 任务类型(1:导出任务)
     */
    public final TableField<TSysTaskRecord, Integer> TYPE = createField(DSL.name("type"), SQLDataType.INTEGER, this, "任务类型(1:导出任务)");

    /**
     * The column <code>bcd.t_sys_task.percent</code>. 任务处理进度
     */
    public final TableField<TSysTaskRecord, Double> PERCENT = createField(DSL.name("percent"), SQLDataType.FLOAT.nullable(false), this, "任务处理进度");

    /**
     * The column <code>bcd.t_sys_task.message</code>. 任务信息(失败时记录失败原因)
     */
    public final TableField<TSysTaskRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.VARCHAR(255), this, "任务信息(失败时记录失败原因)");

    /**
     * The column <code>bcd.t_sys_task.start_time</code>. 任务开始时间
     */
    public final TableField<TSysTaskRecord, LocalDateTime> START_TIME = createField(DSL.name("start_time"), SQLDataType.LOCALDATETIME(0), this, "任务开始时间");

    /**
     * The column <code>bcd.t_sys_task.finish_time</code>. 任务完成时间
     */
    public final TableField<TSysTaskRecord, LocalDateTime> FINISH_TIME = createField(DSL.name("finish_time"), SQLDataType.LOCALDATETIME(0), this, "任务完成时间");

    /**
     * The column <code>bcd.t_sys_task.create_time</code>. 创建时间
     */
    public final TableField<TSysTaskRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>bcd.t_sys_task.result</code>.
     * 任务执行结果(不同的任务类型结果不同、记录导出任务这里存储的是导出文件在文件服务器的路径)
     */
    public final TableField<TSysTaskRecord, String> RESULT = createField(DSL.name("result"), SQLDataType.VARCHAR(255), this, "任务执行结果(不同的任务类型结果不同、记录导出任务这里存储的是导出文件在文件服务器的路径)");

    /**
     * The column <code>bcd.t_sys_task.create_user_id</code>. 创建人id
     */
    public final TableField<TSysTaskRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT, this, "创建人id");

    /**
     * The column <code>bcd.t_sys_task.create_user_name</code>. 创建人姓名
     */
    public final TableField<TSysTaskRecord, String> CREATE_USER_NAME = createField(DSL.name("create_user_name"), SQLDataType.VARCHAR(50), this, "创建人姓名");

    private TSysTask(Name alias, Table<TSysTaskRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TSysTask(Name alias, Table<TSysTaskRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bcd.t_sys_task</code> table reference
     */
    public TSysTask(String alias) {
        this(DSL.name(alias), T_SYS_TASK);
    }

    /**
     * Create an aliased <code>bcd.t_sys_task</code> table reference
     */
    public TSysTask(Name alias) {
        this(alias, T_SYS_TASK);
    }

    /**
     * Create a <code>bcd.t_sys_task</code> table reference
     */
    public TSysTask() {
        this(DSL.name("t_sys_task"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Bcd.BCD;
    }

    @Override
    public Identity<TSysTaskRecord, ULong> getIdentity() {
        return (Identity<TSysTaskRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<TSysTaskRecord> getPrimaryKey() {
        return Keys.KEY_T_SYS_TASK_PRIMARY;
    }

    @Override
    public TSysTask as(String alias) {
        return new TSysTask(DSL.name(alias), this);
    }

    @Override
    public TSysTask as(Name alias) {
        return new TSysTask(alias, this);
    }

    @Override
    public TSysTask as(Table<?> alias) {
        return new TSysTask(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysTask rename(String name) {
        return new TSysTask(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysTask rename(Name name) {
        return new TSysTask(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysTask rename(Table<?> name) {
        return new TSysTask(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysTask where(Condition condition) {
        return new TSysTask(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysTask where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysTask where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysTask where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysTask where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysTask where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysTask where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysTask where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysTask whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysTask whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
