/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables;


import cn.bcd.lib.jooq.generate.Bcd;
import cn.bcd.lib.jooq.generate.Keys;
import cn.bcd.lib.jooq.generate.tables.records.TSysMenuPermissionRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 菜单与权限关联关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysMenuPermission extends TableImpl<TSysMenuPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bcd.t_sys_menu_permission</code>
     */
    public static final TSysMenuPermission T_SYS_MENU_PERMISSION = new TSysMenuPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSysMenuPermissionRecord> getRecordType() {
        return TSysMenuPermissionRecord.class;
    }

    /**
     * The column <code>bcd.t_sys_menu_permission.menu_id</code>. 关联菜单id
     */
    public final TableField<TSysMenuPermissionRecord, Long> MENU_ID = createField(DSL.name("menu_id"), SQLDataType.BIGINT.nullable(false), this, "关联菜单id");

    /**
     * The column <code>bcd.t_sys_menu_permission.permission_id</code>. 关联权限id
     */
    public final TableField<TSysMenuPermissionRecord, Long> PERMISSION_ID = createField(DSL.name("permission_id"), SQLDataType.BIGINT.nullable(false), this, "关联权限id");

    private TSysMenuPermission(Name alias, Table<TSysMenuPermissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TSysMenuPermission(Name alias, Table<TSysMenuPermissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("菜单与权限关联关系表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>bcd.t_sys_menu_permission</code> table reference
     */
    public TSysMenuPermission(String alias) {
        this(DSL.name(alias), T_SYS_MENU_PERMISSION);
    }

    /**
     * Create an aliased <code>bcd.t_sys_menu_permission</code> table reference
     */
    public TSysMenuPermission(Name alias) {
        this(alias, T_SYS_MENU_PERMISSION);
    }

    /**
     * Create a <code>bcd.t_sys_menu_permission</code> table reference
     */
    public TSysMenuPermission() {
        this(DSL.name("t_sys_menu_permission"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Bcd.BCD;
    }

    @Override
    public UniqueKey<TSysMenuPermissionRecord> getPrimaryKey() {
        return Keys.KEY_T_SYS_MENU_PERMISSION_PRIMARY;
    }

    @Override
    public TSysMenuPermission as(String alias) {
        return new TSysMenuPermission(DSL.name(alias), this);
    }

    @Override
    public TSysMenuPermission as(Name alias) {
        return new TSysMenuPermission(alias, this);
    }

    @Override
    public TSysMenuPermission as(Table<?> alias) {
        return new TSysMenuPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysMenuPermission rename(String name) {
        return new TSysMenuPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysMenuPermission rename(Name name) {
        return new TSysMenuPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSysMenuPermission rename(Table<?> name) {
        return new TSysMenuPermission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenuPermission where(Condition condition) {
        return new TSysMenuPermission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenuPermission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenuPermission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenuPermission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysMenuPermission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysMenuPermission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysMenuPermission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TSysMenuPermission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenuPermission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TSysMenuPermission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
