/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate;


import cn.bcd.lib.jooq.generate.tables.TSysMenu;
import cn.bcd.lib.jooq.generate.tables.TSysMenuPermission;
import cn.bcd.lib.jooq.generate.tables.TSysPermission;
import cn.bcd.lib.jooq.generate.tables.TSysRole;
import cn.bcd.lib.jooq.generate.tables.TSysRoleMenu;
import cn.bcd.lib.jooq.generate.tables.TSysTask;
import cn.bcd.lib.jooq.generate.tables.TSysUser;
import cn.bcd.lib.jooq.generate.tables.TSysUserRole;

import java.util.Arrays;
import java.util.List;

import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Bcd extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bcd</code>
     */
    public static final Bcd BCD = new Bcd();

    /**
     * 菜单表
     */
    public final TSysMenu T_SYS_MENU = TSysMenu.T_SYS_MENU;

    /**
     * 菜单与权限关联关系表
     */
    public final TSysMenuPermission T_SYS_MENU_PERMISSION = TSysMenuPermission.T_SYS_MENU_PERMISSION;

    /**
     * 角色与权限关系表
     */
    public final TSysPermission T_SYS_PERMISSION = TSysPermission.T_SYS_PERMISSION;

    /**
     * 角色表
     */
    public final TSysRole T_SYS_ROLE = TSysRole.T_SYS_ROLE;

    /**
     * 角色与菜单关联关系表
     */
    public final TSysRoleMenu T_SYS_ROLE_MENU = TSysRoleMenu.T_SYS_ROLE_MENU;

    /**
     * The table <code>bcd.t_sys_task</code>.
     */
    public final TSysTask T_SYS_TASK = TSysTask.T_SYS_TASK;

    /**
     * 用户基础信息表
     */
    public final TSysUser T_SYS_USER = TSysUser.T_SYS_USER;

    /**
     * 用户与角色关联关系表
     */
    public final TSysUserRole T_SYS_USER_ROLE = TSysUserRole.T_SYS_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Bcd() {
        super(DSL.name("bcd"), null, DSL.comment(""));
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TSysMenu.T_SYS_MENU,
            TSysMenuPermission.T_SYS_MENU_PERMISSION,
            TSysPermission.T_SYS_PERMISSION,
            TSysRole.T_SYS_ROLE,
            TSysRoleMenu.T_SYS_ROLE_MENU,
            TSysTask.T_SYS_TASK,
            TSysUser.T_SYS_USER,
            TSysUserRole.T_SYS_USER_ROLE
        );
    }
}
