/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate;


import cn.bcd.lib.jooq.generate.tables.TSysMenu;
import cn.bcd.lib.jooq.generate.tables.TSysMenuPermission;
import cn.bcd.lib.jooq.generate.tables.TSysPermission;
import cn.bcd.lib.jooq.generate.tables.TSysRole;
import cn.bcd.lib.jooq.generate.tables.TSysRoleMenu;
import cn.bcd.lib.jooq.generate.tables.TSysTask;
import cn.bcd.lib.jooq.generate.tables.TSysUser;
import cn.bcd.lib.jooq.generate.tables.TSysUserRole;
import cn.bcd.lib.jooq.generate.tables.records.TSysMenuPermissionRecord;
import cn.bcd.lib.jooq.generate.tables.records.TSysMenuRecord;
import cn.bcd.lib.jooq.generate.tables.records.TSysPermissionRecord;
import cn.bcd.lib.jooq.generate.tables.records.TSysRoleMenuRecord;
import cn.bcd.lib.jooq.generate.tables.records.TSysRoleRecord;
import cn.bcd.lib.jooq.generate.tables.records.TSysTaskRecord;
import cn.bcd.lib.jooq.generate.tables.records.TSysUserRecord;
import cn.bcd.lib.jooq.generate.tables.records.TSysUserRoleRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in bcd.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TSysMenuRecord> KEY_T_SYS_MENU_PRIMARY = Internal.createUniqueKey(TSysMenu.T_SYS_MENU, DSL.name("KEY_t_sys_menu_PRIMARY"), new TableField[] { TSysMenu.T_SYS_MENU.ID }, true);
    public static final UniqueKey<TSysMenuPermissionRecord> KEY_T_SYS_MENU_PERMISSION_PRIMARY = Internal.createUniqueKey(TSysMenuPermission.T_SYS_MENU_PERMISSION, DSL.name("KEY_t_sys_menu_permission_PRIMARY"), new TableField[] { TSysMenuPermission.T_SYS_MENU_PERMISSION.MENU_ID, TSysMenuPermission.T_SYS_MENU_PERMISSION.PERMISSION_ID }, true);
    public static final UniqueKey<TSysPermissionRecord> KEY_T_SYS_PERMISSION_PRIMARY = Internal.createUniqueKey(TSysPermission.T_SYS_PERMISSION, DSL.name("KEY_t_sys_permission_PRIMARY"), new TableField[] { TSysPermission.T_SYS_PERMISSION.ID }, true);
    public static final UniqueKey<TSysRoleRecord> KEY_T_SYS_ROLE_PRIMARY = Internal.createUniqueKey(TSysRole.T_SYS_ROLE, DSL.name("KEY_t_sys_role_PRIMARY"), new TableField[] { TSysRole.T_SYS_ROLE.ID }, true);
    public static final UniqueKey<TSysRoleMenuRecord> KEY_T_SYS_ROLE_MENU_PRIMARY = Internal.createUniqueKey(TSysRoleMenu.T_SYS_ROLE_MENU, DSL.name("KEY_t_sys_role_menu_PRIMARY"), new TableField[] { TSysRoleMenu.T_SYS_ROLE_MENU.ROLE_ID, TSysRoleMenu.T_SYS_ROLE_MENU.MENU_ID }, true);
    public static final UniqueKey<TSysTaskRecord> KEY_T_SYS_TASK_PRIMARY = Internal.createUniqueKey(TSysTask.T_SYS_TASK, DSL.name("KEY_t_sys_task_PRIMARY"), new TableField[] { TSysTask.T_SYS_TASK.ID }, true);
    public static final UniqueKey<TSysUserRecord> KEY_T_SYS_USER_PRIMARY = Internal.createUniqueKey(TSysUser.T_SYS_USER, DSL.name("KEY_t_sys_user_PRIMARY"), new TableField[] { TSysUser.T_SYS_USER.ID }, true);
    public static final UniqueKey<TSysUserRoleRecord> KEY_T_SYS_USER_ROLE_PRIMARY = Internal.createUniqueKey(TSysUserRole.T_SYS_USER_ROLE, DSL.name("KEY_t_sys_user_role_PRIMARY"), new TableField[] { TSysUserRole.T_SYS_USER_ROLE.USER_ID, TSysUserRole.T_SYS_USER_ROLE.ROLE_ID }, true);
}
