/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate;


import cn.bcd.lib.jooq.generate.tables.TSysMenu;
import cn.bcd.lib.jooq.generate.tables.TSysMenuPermission;
import cn.bcd.lib.jooq.generate.tables.TSysPermission;
import cn.bcd.lib.jooq.generate.tables.TSysRole;
import cn.bcd.lib.jooq.generate.tables.TSysRoleMenu;
import cn.bcd.lib.jooq.generate.tables.TSysTask;
import cn.bcd.lib.jooq.generate.tables.TSysUser;
import cn.bcd.lib.jooq.generate.tables.TSysUserRole;


/**
 * Convenience access to all tables in bcd.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 菜单表
     */
    public static final TSysMenu T_SYS_MENU = TSysMenu.T_SYS_MENU;

    /**
     * 菜单与权限关联关系表
     */
    public static final TSysMenuPermission T_SYS_MENU_PERMISSION = TSysMenuPermission.T_SYS_MENU_PERMISSION;

    /**
     * 角色与权限关系表
     */
    public static final TSysPermission T_SYS_PERMISSION = TSysPermission.T_SYS_PERMISSION;

    /**
     * 角色表
     */
    public static final TSysRole T_SYS_ROLE = TSysRole.T_SYS_ROLE;

    /**
     * 角色与菜单关联关系表
     */
    public static final TSysRoleMenu T_SYS_ROLE_MENU = TSysRoleMenu.T_SYS_ROLE_MENU;

    /**
     * The table <code>bcd.t_sys_task</code>.
     */
    public static final TSysTask T_SYS_TASK = TSysTask.T_SYS_TASK;

    /**
     * 用户基础信息表
     */
    public static final TSysUser T_SYS_USER = TSysUser.T_SYS_USER;

    /**
     * 用户与角色关联关系表
     */
    public static final TSysUserRole T_SYS_USER_ROLE = TSysUserRole.T_SYS_USER_ROLE;
}
