/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables.records;


import cn.bcd.lib.jooq.generate.tables.TSysRoleMenu;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色与菜单关联关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysRoleMenuRecord extends UpdatableRecordImpl<TSysRoleMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bcd.t_sys_role_menu.role_id</code>. 关联角色id
     */
    public void setRoleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role_menu.role_id</code>. 关联角色id
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bcd.t_sys_role_menu.menu_id</code>. 关联菜单id
     */
    public void setMenuId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role_menu.menu_id</code>. 关联菜单id
     */
    public Long getMenuId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSysRoleMenuRecord
     */
    public TSysRoleMenuRecord() {
        super(TSysRoleMenu.T_SYS_ROLE_MENU);
    }

    /**
     * Create a detached, initialised TSysRoleMenuRecord
     */
    public TSysRoleMenuRecord(Long roleId, Long menuId) {
        super(TSysRoleMenu.T_SYS_ROLE_MENU);

        setRoleId(roleId);
        setMenuId(menuId);
        resetTouchedOnNotNull();
    }
}
