/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables.records;


import cn.bcd.lib.jooq.generate.tables.TSysMenu;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 菜单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysMenuRecord extends UpdatableRecordImpl<TSysMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bcd.t_sys_menu.id</code>. 主键
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.id</code>. 主键
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.parent_id</code>. 父菜单id
     */
    public void setParentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.parent_id</code>. 父菜单id
     */
    public Long getParentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.name</code>. 菜单名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.name</code>. 菜单名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.url</code>. url地址
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.url</code>. url地址
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.icon</code>. 图标
     */
    public void setIcon(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.icon</code>. 图标
     */
    public String getIcon() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.order_num</code>. 排序
     */
    public void setOrderNum(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.order_num</code>. 排序
     */
    public Integer getOrderNum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.create_user_id</code>. 创建人id
     */
    public void setCreateUserId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.create_user_id</code>. 创建人id
     */
    public Long getCreateUserId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.create_user_name</code>. 创建人姓名
     */
    public void setCreateUserName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.create_user_name</code>. 创建人姓名
     */
    public String getCreateUserName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.update_user_id</code>. 更新人id
     */
    public void setUpdateUserId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.update_user_id</code>. 更新人id
     */
    public Long getUpdateUserId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>bcd.t_sys_menu.update_user_name</code>. 更新人姓名
     */
    public void setUpdateUserName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu.update_user_name</code>. 更新人姓名
     */
    public String getUpdateUserName() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSysMenuRecord
     */
    public TSysMenuRecord() {
        super(TSysMenu.T_SYS_MENU);
    }

    /**
     * Create a detached, initialised TSysMenuRecord
     */
    public TSysMenuRecord(ULong id, Long parentId, String name, String url, String icon, Integer orderNum, LocalDateTime createTime, Long createUserId, String createUserName, LocalDateTime updateTime, Long updateUserId, String updateUserName) {
        super(TSysMenu.T_SYS_MENU);

        setId(id);
        setParentId(parentId);
        setName(name);
        setUrl(url);
        setIcon(icon);
        setOrderNum(orderNum);
        setCreateTime(createTime);
        setCreateUserId(createUserId);
        setCreateUserName(createUserName);
        setUpdateTime(updateTime);
        setUpdateUserId(updateUserId);
        setUpdateUserName(updateUserName);
        resetTouchedOnNotNull();
    }
}
