/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables.records;


import cn.bcd.lib.jooq.generate.tables.TSysTask;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysTaskRecord extends UpdatableRecordImpl<TSysTaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bcd.t_sys_task.id</code>. 主键
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.id</code>. 主键
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>bcd.t_sys_task.name</code>. 任务名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.name</code>. 任务名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bcd.t_sys_task.status</code>.
     * 任务状态(1:等待中;2:执行中;3:任务被终止;4:已完成;5:执行失败)
     */
    public void setStatus(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.status</code>.
     * 任务状态(1:等待中;2:执行中;3:任务被终止;4:已完成;5:执行失败)
     */
    public Integer getStatus() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>bcd.t_sys_task.type</code>. 任务类型(1:导出任务)
     */
    public void setType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.type</code>. 任务类型(1:导出任务)
     */
    public Integer getType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>bcd.t_sys_task.percent</code>. 任务处理进度
     */
    public void setPercent(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.percent</code>. 任务处理进度
     */
    public Double getPercent() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>bcd.t_sys_task.message</code>. 任务信息(失败时记录失败原因)
     */
    public void setMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.message</code>. 任务信息(失败时记录失败原因)
     */
    public String getMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bcd.t_sys_task.start_time</code>. 任务开始时间
     */
    public void setStartTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.start_time</code>. 任务开始时间
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>bcd.t_sys_task.finish_time</code>. 任务完成时间
     */
    public void setFinishTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.finish_time</code>. 任务完成时间
     */
    public LocalDateTime getFinishTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>bcd.t_sys_task.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>bcd.t_sys_task.result</code>.
     * 任务执行结果(不同的任务类型结果不同、记录导出任务这里存储的是导出文件在文件服务器的路径)
     */
    public void setResult(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.result</code>.
     * 任务执行结果(不同的任务类型结果不同、记录导出任务这里存储的是导出文件在文件服务器的路径)
     */
    public String getResult() {
        return (String) get(9);
    }

    /**
     * Setter for <code>bcd.t_sys_task.create_user_id</code>. 创建人id
     */
    public void setCreateUserId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.create_user_id</code>. 创建人id
     */
    public Long getCreateUserId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>bcd.t_sys_task.create_user_name</code>. 创建人姓名
     */
    public void setCreateUserName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>bcd.t_sys_task.create_user_name</code>. 创建人姓名
     */
    public String getCreateUserName() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSysTaskRecord
     */
    public TSysTaskRecord() {
        super(TSysTask.T_SYS_TASK);
    }

    /**
     * Create a detached, initialised TSysTaskRecord
     */
    public TSysTaskRecord(ULong id, String name, Integer status, Integer type, Double percent, String message, LocalDateTime startTime, LocalDateTime finishTime, LocalDateTime createTime, String result, Long createUserId, String createUserName) {
        super(TSysTask.T_SYS_TASK);

        setId(id);
        setName(name);
        setStatus(status);
        setType(type);
        setPercent(percent);
        setMessage(message);
        setStartTime(startTime);
        setFinishTime(finishTime);
        setCreateTime(createTime);
        setResult(result);
        setCreateUserId(createUserId);
        setCreateUserName(createUserName);
        resetTouchedOnNotNull();
    }
}
