/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables.records;


import cn.bcd.lib.jooq.generate.tables.TSysUserRole;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户与角色关联关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysUserRoleRecord extends UpdatableRecordImpl<TSysUserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bcd.t_sys_user_role.user_id</code>. 关联用户id
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user_role.user_id</code>. 关联用户id
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bcd.t_sys_user_role.role_id</code>. 关联角色id
     */
    public void setRoleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user_role.role_id</code>. 关联角色id
     */
    public Long getRoleId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSysUserRoleRecord
     */
    public TSysUserRoleRecord() {
        super(TSysUserRole.T_SYS_USER_ROLE);
    }

    /**
     * Create a detached, initialised TSysUserRoleRecord
     */
    public TSysUserRoleRecord(Long userId, Long roleId) {
        super(TSysUserRole.T_SYS_USER_ROLE);

        setUserId(userId);
        setRoleId(roleId);
        resetTouchedOnNotNull();
    }
}
