/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables.records;


import cn.bcd.lib.jooq.generate.tables.TSysPermission;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 角色与权限关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysPermissionRecord extends UpdatableRecordImpl<TSysPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bcd.t_sys_permission.id</code>. id
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcd.t_sys_permission.id</code>. id
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>bcd.t_sys_permission.name</code>. 权限名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcd.t_sys_permission.name</code>. 权限名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bcd.t_sys_permission.resource</code>. 资源
     */
    public void setResource(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcd.t_sys_permission.resource</code>. 资源
     */
    public String getResource() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bcd.t_sys_permission.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcd.t_sys_permission.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>bcd.t_sys_permission.create_user_id</code>. 创建人id
     */
    public void setCreateUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcd.t_sys_permission.create_user_id</code>. 创建人id
     */
    public Long getCreateUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>bcd.t_sys_permission.create_user_name</code>. 创建人姓名
     */
    public void setCreateUserName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcd.t_sys_permission.create_user_name</code>. 创建人姓名
     */
    public String getCreateUserName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bcd.t_sys_permission.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>bcd.t_sys_permission.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>bcd.t_sys_permission.update_user_id</code>. 更新人id
     */
    public void setUpdateUserId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>bcd.t_sys_permission.update_user_id</code>. 更新人id
     */
    public Long getUpdateUserId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>bcd.t_sys_permission.update_user_name</code>. 更新人姓名
     */
    public void setUpdateUserName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bcd.t_sys_permission.update_user_name</code>. 更新人姓名
     */
    public String getUpdateUserName() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSysPermissionRecord
     */
    public TSysPermissionRecord() {
        super(TSysPermission.T_SYS_PERMISSION);
    }

    /**
     * Create a detached, initialised TSysPermissionRecord
     */
    public TSysPermissionRecord(ULong id, String name, String resource, LocalDateTime createTime, Long createUserId, String createUserName, LocalDateTime updateTime, Long updateUserId, String updateUserName) {
        super(TSysPermission.T_SYS_PERMISSION);

        setId(id);
        setName(name);
        setResource(resource);
        setCreateTime(createTime);
        setCreateUserId(createUserId);
        setCreateUserName(createUserName);
        setUpdateTime(updateTime);
        setUpdateUserId(updateUserId);
        setUpdateUserName(updateUserName);
        resetTouchedOnNotNull();
    }
}
