/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables.records;


import cn.bcd.lib.jooq.generate.tables.TSysMenuPermission;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 菜单与权限关联关系表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysMenuPermissionRecord extends UpdatableRecordImpl<TSysMenuPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bcd.t_sys_menu_permission.menu_id</code>. 关联菜单id
     */
    public void setMenuId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu_permission.menu_id</code>. 关联菜单id
     */
    public Long getMenuId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>bcd.t_sys_menu_permission.permission_id</code>. 关联权限id
     */
    public void setPermissionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcd.t_sys_menu_permission.permission_id</code>. 关联权限id
     */
    public Long getPermissionId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSysMenuPermissionRecord
     */
    public TSysMenuPermissionRecord() {
        super(TSysMenuPermission.T_SYS_MENU_PERMISSION);
    }

    /**
     * Create a detached, initialised TSysMenuPermissionRecord
     */
    public TSysMenuPermissionRecord(Long menuId, Long permissionId) {
        super(TSysMenuPermission.T_SYS_MENU_PERMISSION);

        setMenuId(menuId);
        setPermissionId(permissionId);
        resetTouchedOnNotNull();
    }
}
