/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables.records;


import cn.bcd.lib.jooq.generate.tables.TSysUser;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 用户基础信息表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysUserRecord extends UpdatableRecordImpl<TSysUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bcd.t_sys_user.id</code>. 主键
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.id</code>. 主键
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>bcd.t_sys_user.username</code>. 用户名
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.username</code>. 用户名
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bcd.t_sys_user.password</code>. 密码
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bcd.t_sys_user.email</code>. 邮箱
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bcd.t_sys_user.phone</code>. 手机号
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.phone</code>. 手机号
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bcd.t_sys_user.real_name</code>. 真实姓名
     */
    public void setRealName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.real_name</code>. 真实姓名
     */
    public String getRealName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bcd.t_sys_user.sex</code>. 性别
     */
    public void setSex(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.sex</code>. 性别
     */
    public String getSex() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bcd.t_sys_user.birthday</code>. 生日
     */
    public void setBirthday(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.birthday</code>. 生日
     */
    public LocalDateTime getBirthday() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>bcd.t_sys_user.card_number</code>. 身份证号
     */
    public void setCardNumber(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.card_number</code>. 身份证号
     */
    public String getCardNumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bcd.t_sys_user.status</code>. 是否可用(1:可用,0:禁用)
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.status</code>. 是否可用(1:可用,0:禁用)
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>bcd.t_sys_user.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>bcd.t_sys_user.create_user_id</code>. 创建人id
     */
    public void setCreateUserId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.create_user_id</code>. 创建人id
     */
    public Long getCreateUserId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>bcd.t_sys_user.create_user_name</code>. 创建人姓名
     */
    public void setCreateUserName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.create_user_name</code>. 创建人姓名
     */
    public String getCreateUserName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>bcd.t_sys_user.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>bcd.t_sys_user.update_user_id</code>. 更新人id
     */
    public void setUpdateUserId(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.update_user_id</code>. 更新人id
     */
    public Long getUpdateUserId() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>bcd.t_sys_user.update_user_name</code>. 更新人姓名
     */
    public void setUpdateUserName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>bcd.t_sys_user.update_user_name</code>. 更新人姓名
     */
    public String getUpdateUserName() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSysUserRecord
     */
    public TSysUserRecord() {
        super(TSysUser.T_SYS_USER);
    }

    /**
     * Create a detached, initialised TSysUserRecord
     */
    public TSysUserRecord(ULong id, String username, String password, String email, String phone, String realName, String sex, LocalDateTime birthday, String cardNumber, Integer status, LocalDateTime createTime, Long createUserId, String createUserName, LocalDateTime updateTime, Long updateUserId, String updateUserName) {
        super(TSysUser.T_SYS_USER);

        setId(id);
        setUsername(username);
        setPassword(password);
        setEmail(email);
        setPhone(phone);
        setRealName(realName);
        setSex(sex);
        setBirthday(birthday);
        setCardNumber(cardNumber);
        setStatus(status);
        setCreateTime(createTime);
        setCreateUserId(createUserId);
        setCreateUserName(createUserName);
        setUpdateTime(updateTime);
        setUpdateUserId(updateUserId);
        setUpdateUserName(updateUserName);
        resetTouchedOnNotNull();
    }
}
