/*
 * This file is generated by jOOQ.
 */
package cn.bcd.lib.jooq.generate.tables.records;


import cn.bcd.lib.jooq.generate.tables.TSysRole;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TSysRoleRecord extends UpdatableRecordImpl<TSysRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bcd.t_sys_role.id</code>. 主键
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.id</code>. 主键
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>bcd.t_sys_role.name</code>. 角色名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.name</code>. 角色名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bcd.t_sys_role.code</code>. 编码
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.code</code>. 编码
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bcd.t_sys_role.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bcd.t_sys_role.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>bcd.t_sys_role.create_user_id</code>. 创建人id
     */
    public void setCreateUserId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.create_user_id</code>. 创建人id
     */
    public Long getCreateUserId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>bcd.t_sys_role.create_user_name</code>. 创建人姓名
     */
    public void setCreateUserName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.create_user_name</code>. 创建人姓名
     */
    public String getCreateUserName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bcd.t_sys_role.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>bcd.t_sys_role.update_user_id</code>. 更新人id
     */
    public void setUpdateUserId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.update_user_id</code>. 更新人id
     */
    public Long getUpdateUserId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>bcd.t_sys_role.update_user_name</code>. 更新人姓名
     */
    public void setUpdateUserName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bcd.t_sys_role.update_user_name</code>. 更新人姓名
     */
    public String getUpdateUserName() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSysRoleRecord
     */
    public TSysRoleRecord() {
        super(TSysRole.T_SYS_ROLE);
    }

    /**
     * Create a detached, initialised TSysRoleRecord
     */
    public TSysRoleRecord(ULong id, String name, String code, String remark, LocalDateTime createTime, Long createUserId, String createUserName, LocalDateTime updateTime, Long updateUserId, String updateUserName) {
        super(TSysRole.T_SYS_ROLE);

        setId(id);
        setName(name);
        setCode(code);
        setRemark(remark);
        setCreateTime(createTime);
        setCreateUserId(createUserId);
        setCreateUserName(createUserName);
        setUpdateTime(updateTime);
        setUpdateUserId(updateUserId);
        setUpdateUserName(updateUserName);
        resetTouchedOnNotNull();
    }
}
