spring:
  application:
    name: app-mqtt-server

mqtt:
  server:
    enabled: true
    bind-address: 0.0.0.0
    port: 1883
    max-packet-size: 1048576
    max-client-id-length: 65535
    authentication:
      type: anonymous
    authorization:
      type: allow-all
    persistence:
      retained-message:
        type: sqlite
        sqlite:
          database-path: data/mqtt-retained.db
