dependencies {
    implementation platform(libs.spring.boot.dependencies)
    implementation platform(libs.prometheus.bom)
    implementation libs.prometheus.metrics.core
    implementation libs.prometheus.metrics.instrumentation.jvm
    implementation libs.prometheus.metrics.exporter.httpserver
    implementation libs.spring.boot.starter
    implementation libs.slf4j.api
}
