dependencies {
    implementation platform(libs.spring.boot.dependencies)
    implementation platform(libs.netty.bom)
    implementation project(":Lib-Base")
    implementation libs.spring.boot.starter
    implementation libs.spring.boot.starter.log4j2
    implementation libs.netty.transport
    implementation libs.netty.handler
    implementation libs.netty.codec.mqtt
    implementation libs.sqlite

    testImplementation libs.spring.boot.starter.test
}
