server:
  port: 9999
  compression:
    enabled: true
    mime-types: application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain
    min-response-size: 1024
  servlet:
    session:
      timeout: 1800

spring:
  application:
    name: business-process-gateway
  threads:
    virtual:
      enabled: true
  # 允许循环依赖
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      chain:
        cache: false
  profiles:
    active: dev
  freemarker:
    checkTemplateLocation: false
  data:
    #redis配置
    #如果都进行了配置,加载的先后顺序为:
    #sentinel>cluster>single
    redis:
      ssl:
        enabled: false
      repositories:
        enabled: false
      #公用配置
      database: 0
      timeout: 60000
      password: wq
      #异步lettuce连接池(默认)
      lettuce:
        pool:
          maxIdle: 8
          minIdle: 0
          maxActive: 8
          maxWait: -1
        shutdown-timeout: 100ms
      #单机配置
      host: 10.0.11.50
      port: 36379
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.11.50:8848
        ip: 10.0.11.50
        port: 9999
    loadbalancer:
      ribbon:
        enable: false

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)、在前面加上前缀、可以区分系统、影响存储到redis中的key
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 同一账号可同时在线的最大数量
  max-login-count: -1
  # 配置token读取的位置
  is-read-body: false
  is-read-header: false
  is-read-cookie: true
