server:
  port: 7777
  compression:
    enabled: true
    mime-types: application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain
    min-response-size: 1024
  servlet:
    session:
      timeout: 1800
spring:
  application:
    name: business-process-openapi
  threads:
    virtual:
      enabled: true
  # 允许循环依赖
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      chain:
        cache: false
  profiles:
    active: dev
  freemarker:
    checkTemplateLocation: false
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
    #mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/bcd?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&generateSimpleParameterMetadata=true&allowPublicKeyRetrieval=True
    username: root
    password: root

  #  jdbcTemplate配置
  jdbc:
    template:
      fetch-size: -1
      max-rows: -1
      query-timeout:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        ip: 127.0.0.1
        port: 8888
    sentinel:
      log:
        dir: logs/csp
      transport:
        port: 8889
        dashboard: 127.0.0.1:33333


springdoc:
  packages-to-scan:
    - cn.bcd
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

monitor:
  request-topic: monitorRequest
  response-list: monitorResponse
  server-id: ${spring.application.name}
  server-type: 3
