spring:
  application:
    name: server-monitor-collector
  threads:
    virtual:
      enabled: true
  # 允许循环依赖
  main:
    allow-circular-references: true
  profiles:
    active: dev
  freemarker:
    checkTemplateLocation: false
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
    #mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.23.129:3306/bcd?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&generateSimpleParameterMetadata=true&allowPublicKeyRetrieval=True
    username: root
    password: bcd
    #pgsql:
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://127.0.0.1:5432/msbf
  #    username: root
  #    password: 123456

  #  jdbcTemplate配置
  jdbc:
    template:
      fetch-size: -1
      max-rows: -1
      query-timeout:
  data:
    #redis配置
    #如果都进行了配置,加载的先后顺序为:
    #sentinel>cluster>single
    redis:
      ssl:
        enabled: false
      repositories:
        enabled: false
      #公用配置
      database: 0
      timeout: 60000
      password: bcd
      #异步lettuce连接池(默认)
      lettuce:
        pool:
          maxIdle: 8
          minIdle: 0
          maxActive: 8
          maxWait: -1
        shutdown-timeout: 100ms
      #主从配置
      #     sentinel:
      #       master: myMaster
      #       nodes: 127.0.0.1:23679,127.0.0.1:23680,127.0.0.1:23681
      #集群配置
      cluster:
        maxRedirects: 3
        nodes:
          - 192.168.23.129:7001
          - 192.168.23.129:7002
          - 192.168.23.129:7003
          - 192.168.23.129:7004
          - 192.168.23.129:7005
          - 192.168.23.129:7006
      #单机配置
  #      host: 192.168.23.129
  #      port: 6379

lib:
  monitor:
    client:
      requestTopic: monitorRequest
      responseList: monitorResponse
      collectCron: 0/15 * * * * *